name: Deploy with API Key

on:
  push:
    branches:
      - main  # 또는 당신의 주 브랜치 이름
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Replace API Key
      env:
        KAKAO_MAP_API_KEY: ${{ secrets.KAKAO_MAP_API_KEY }}
      run: |
        set -e
        sed -i 's|__KAKAO_MAP_API_KEY__|'"${KAKAO_MAP_API_KEY}"'|g' index.html

    - name: Debug - Check API Key Replacement
      run: |
        grep -n "dapi.kakao.com" index.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
